### ISSUE TITLE
Assertion errors due to pointer alignment on 32-bit OS

### ISSUE THREAD

**Issue by bcbarbara** [acados/acados#533] opened 2020-01-09 16:07 UTC
Hello,

I am trying to run the exported C-code of `acados` - generated via its Python interface - on an [Odroid XU4](https://wiki.odroid.com/odroid-xu4/odroid-xu4), but due to the 32-bit Ubuntu OS I have installed (which is the only one supported), I am getting errors associated to the checks that pointers should be aligned to 8 bytes. 

![error](https://user-images.githubusercontent.com/50755258/72082672-cc5ec180-3300-11ea-812c-d49f1cdf302c.png)

Is there any possibility to port `acados` to 32-bit system?

**Comment by zanellia** [comment] 2020-01-09 16:27
Hey Barbara! Could you printf sizeof(blasfeo_dmat)? The memory should be aligned to 8 bytes by construction unless variables of certain types change in size (I guess integers and pointers are of dimension 4 bytes in your case).

**Comment by bcbarbara** [comment] 2020-01-09 18:31
Hey Andrea, I just checked the size of the struct blasfeo_dmat and it is 32.

**Comment by zanellia** [comment] 2020-01-10 09:14
Then the problem is likely to be related to assign functions in acados. The same issue has been discussed here https://github.com/acados/acados/issues/317 and a potential solution is proposed here 
https://github.com/acados/acados/pull/408. I can try to fix that PR.

**Comment by giaf** [comment] 2020-01-10 09:21
@zanellia there is no point in fixing that PR, it is outdated and it was causing issues with Travis, that's why it never got merged.

What we need to know to fix @bcbarbara 's issue is where (file + line of code) the assertion fails, and have a look at what is going on there.

**Comment by zanellia** [comment] 2020-01-10 09:26
@giaf I have read the conversation and understand the reason why the PR was not merged. However, it's 12 lines of additions and 4 deletions, I thought it might still be a good starting point. If you know how to fix the problem, please go ahead :)

**Comment by zanellia** [comment] 2020-01-10 09:34
@bcbarbara could you try to obtain a stack trace with gdb (see e.g. this https://senarvi.github.io/stack-trace-with-gdb/)? That's going to tell us where the assertion fails.

**Comment by bcbarbara** [comment] 2020-01-10 10:01
Sure, @zanellia. Come back with the results to you ASAP!

**Comment by bcbarbara** [comment] 2020-01-10 10:02
Sure, @zanellia. I'll come back with the results ASAP!

**Comment by bcbarbara** [comment] 2020-01-10 10:19
Hello guys, that's what I've got:

<img width="687" alt="Screenshot 2020-01-10 at 11 18 09" src="https://user-images.githubusercontent.com/50755258/72145495-f06ee100-339a-11ea-96c6-c2ca160e86e5.png">

**Comment by zanellia** [comment] 2020-01-10 11:23
alright, so the (first) problem should be in `external_function_param_casadi_assign` at this line: https://github.com/acados/acados/blob/master/acados/utils/external_function_generic.c#L947 (the first call to `assign_and_advance_double_ptrs` should pass since the alignment is enforced explicitly). @giaf do we really need double pointers to be 8-byte aligned? If so, it might make sense to add a for loop with an explicit alignment at every iteration (that would do nothing on a 64-bit system).

**Comment by tmmsartor** [comment] 2020-01-13 11:54
@bcbarbara acados c examples are running on your platform?

**Comment by FreyJo** [comment] 2020-04-24 16:31
Issues with 32 Bit architectures are now tracked here:
https://github.com/acados/acados/issues/599
Sorry that we couldnt fix the issues in time..

**Closed by FreyJo** 2020-04-24 16:31 UTC
